version: '3.8'

services:
  api-gateway:
    build: .
    container_name: api-gateway-app
    ports:
      - 8083:8082
  gestorObras:
    image: gestorobras-app:lastest
    container_name: gestorobras-app
    ports:
      - 8081:8080
  gestorHerramientas:
    image: gestorherramientas-app:lastest
    container_name: gestorherramientas-app
    ports:
      - 8082:8081
  gestorPersonal:
      image: gestorpersonal-app:lastest
      container_name: gestorpersonal-app
      ports:
      - 8082:8082
  discoveryServer:
    image: discoveryserver-app:lastest
    container_name: discoveryserver-app
    ports:
      - 8084:8085


